modules:
  - name: "Click here to start the study"
    lessons:
      - name: "Getting Started"
        file: "00-getting-started.md"
        shortName: "about"
      - name: "Consent"
        file: "01-consent.md"
        shortName: "consent"
      - name: "Pre-Survey"
        file: "02-pre-questionnaire.md"
        shortName: "pre-survey"
      - name: "Instructions"
        file: "03-instructions.md"
        shortName: "instructions"
      - name: "Lesson 1: Operators"
        file: "04-lesson-1-operators.md"
        shortName: "lesson-1"
      - name: "Lesson 2: Variables"
        file: "05-lesson-2-variables.md"
        shortName: "lesson-2"
      - name: "Lesson 3: Vectors and Functions"
        file: "06-lesson-3-vectors-and-functions.md"
        shortName: "lesson-3"
      - name: "Lesson 4: Data Frames and More Functions"
        file: "07-lesson-4-data-frames.md"
        shortName: "lesson-4"
      - name: "Lesson Summary"
        file: "08-lesson-summary.md"
        shortName: "lesson-summary"
      - name: "Landing 1"
        file: "09-landing-1.md"
        shortName: "landing-1"
      - name: "Extra 1"
        file: "10-extra-1.md"
        shortName: "extra-1"
      - name: "Landing 2"
        file: "11-landing-2.md"
        shortName: "landing-2"
      - name: "Extra 2"
        file: "12-extra-2.md"
        shortName: "extra-2"
      - name: "Landing 3"
        file: "13-landing-3.md"
        shortName: "landing-3"
      - name: "Extra 3"
        file: "14-extra-3.md"
        shortName: "extra-3"
      - name: "Landing 4"
        file: "15-landing-4.md"
        shortName: "landing-4"
      - name: "Extra 4"
        file: "16-extra-4.md"
        shortName: "extra-4"
      - name: "Landing 5"
        file: "17-landing-5.md"
        shortName: "landing-5"
      - name: "Extra 5"
        file: "18-extra-5.md"
        shortName: "extra-5"
      - name: "Landing 6"
        file: "19-landing-6.md"
        shortName: "landing-6"
      - name: "Extra 6"
        file: "20-extra-6.md"
        shortName: "extra-6"        
      - name: "Landing 7"
        file: "21-landing-7.md"
        shortName: "landing-7"
      - name: "Extra 7"
        file: "22-extra-7.md"
        shortName: "extra-7"        
      - name: "Landing 8"
        file: "23-landing-8.md"
        shortName: "landing-8"
      - name: "Extra 8"
        file: "24-extra-8.md"
        shortName: "extra-8"           
      - name: "Landing 9"
        file: "25-landing-9.md"
        shortName: "landing-7"
      - name: "Extra 9"
        file: "26-extra-9.md"
        shortName: "extra-9"        
      - name: "Landing 10"
        file: "27-landing-10.md"
        shortName: "landing-10"
      - name: "Extra 10"
        file: "28-extra-10.md"
        shortName: "extra-10"         
        
        
        
        
        
        
        